#!/usr/bin/python3

# This script is used to update the docs in docs/reference
# which are served at http://developer.linuxmint.com/xapps/reference/index.html.

import os
import sys

SRC="debian/tmp/usr/share/gtk-doc/html/libxapp/"

if not os.path.exists(SRC):
    print("Build first, with dpkg-buildpackage")
    sys.exit(1)

os.system("rm -rf docs/reference/*")
os.system("cp -R %s/* docs/reference/" % SRC)

print ("Docs updated, you can now commit and push.")
