#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('XApp', '1.0')

from gi.repository import Gtk, XApp

if __name__ == '__main__':
    dialog = XApp.IconChooserDialog()
    response = dialog.run_with_category('Apps')

    if response == Gtk.ResponseType.OK:
        print(dialog.get_icon_string())
    else:
        print('Dialog Cancelled')
