#!/usr/bin/python3

import gi
gi.require_version('XApp', '1.0')
from gi.repository import XApp
from gi.repository import GLib, GObject
import sys

class App(GObject.Object):

    def __init__(self):
        super(App, self).__init__()
        self.status_icon = XApp.StatusIcon()
        #self.status_icon.set_name("xapp-status-icon") # optional, defaults to program name, not shown to users
        self.status_icon.set_icon_name("folder-symbolic")
        self.status_icon.set_tooltip_text("My tooltip text")
        self.status_icon.set_label("label 1")
        self.counter = 1
        self.status_icon.connect("left-click", self.on_left_click)
        self.status_icon.connect("middle-click", self.on_middle_click)
        self.status_icon.connect("right-click", self.on_right_click)

        GLib.timeout_add_seconds(2, self.on_timeout_cb)

    def on_timeout_cb(self):
        self.counter += 1
        self.status_icon.set_label("label %d" % self.counter)
        # self.status_icon.set_visible((self.counter % 2) == 0)
        return True

    def on_left_click(self, status_icon, x, y, time, button):
        print("We were left clicked at %d %d" % (x, y))

    def on_middle_click(self, status_icon, x, y, time, button):
        print("We were middle clicked at %d %d" % (x, y))

    def on_right_click(self, status_icon, x, y, time, button):
        print("We were right clicked at %d %d" % (x, y))

if __name__ == '__main__':
    app = App()
    try:
        GLib.MainLoop().run()
    except KeyboardInterrupt:
        pass
    sys.exit(0)
